name: Terraform Plan
description: Run terraform plan

inputs:
  terraform_version:
    description: Terraform version
    required: true
  tfcmt_version:
    description: tfcmt version
    required: true
  tflint_version:
    description: tflint version
    required: true

runs:
  using: composite

  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Setup tfcmt
      uses: shmokmt/actions-setup-tfcmt@04d5aa6dc61eaa69a4d00257224c9b97f4857819 # v2.1.1
      with:
        version: v${{ inputs.tfcmt_version }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
      with:
        tflint_version: v${{ inputs.tflint_version }}
